### ISSUE TITLE
Data For Culture workshop todos

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-nodes#175]
- [x] port creation shortcuts
- [x] ~~ electron build with built-in npm (next time)~~ 
- [x] sublime text keybindings
- [x] ~~ electron build (next time)~~ 
- [x] white code editor theme?
- [ ] inspector orbiter interference https://github.com/pex-gl/pex-nodes/issues/164
- [x] fix color picker in Safari https://github.com/pex-gl/pex-nodes/issues/183
- [x] don't display arrays > 4 elems in inspector https://github.com/pex-gl/pex-nodes/issues/170
- [x] fix firefox zoom https://github.com/pex-gl/pex-nodes/issues/165
- [x] open server in the browser on start https://github.com/pex-gl/pex-nodes/issues/188
- [x] camera crashing when looking straight down https://github.com/pex-gl/pex-cam/issues/9
- [x] update node template to new port syntax
- [x] Show inspector with published ports in fullscreen mode https://github.com/pex-gl/pex-nodes/issues/189
